{jazzy} example-interfaces: Add action-msgs as build dependency
example-interfaces fails to build with below errors.

| /scratch/sandeep/yocto/2024.2/yp-dev/build-ros/tmp/work/cortexa72-cortexa53-xilinx-linux/example-interfaces/0.12.0-3/recipe-sysroot-native/usr/bin/aarch64-xilinx-linux/../../libexec/aarch64-xilinx-linux/gcc/aarch64-xilinx-linux/13.3.0/ld: /scratch/sandeep/yocto/2024.2/yp-dev/build-ros/tmp/work/cortexa72-cortexa53-xilinx-linux/example-interfaces/0.12.0-3/recipe-sysroot-native/opt/ros/jazzy/lib/libaction_msgs__rosidl_generator_c.so: error adding symbols: file in wrong format
| collect2: error: ld returned 1 exit status
| ninja: build stopped: subcommand failed.
|
| WARNING: /scratch/sandeep/yocto/2024.2/yp-dev/build-ros/tmp/work/cortexa72-cortexa53-xilinx-linux/example-interfaces/0.12.0-3/temp/run.do_compile.1049629:165 exit 1 from 'eval ${DESTDIR:+DESTDIR=${DESTDIR} }VERBOSE=1 cmake --build '/scratch/sandeep/yocto/2024.2/yp-dev/build-ros/tmp/work/cortexa72-cortexa53-xilinx-linux/example-interfaces/0.12.0-3/build' "$@" -- ${EXTRA_OECMAKE_BUILD}'
| WARNING: Backtrace (BB generated script):
| 	#1: cmake_runcmake_build, /scratch/sandeep/yocto/2024.2/yp-dev/build-ros/tmp/work/cortexa72-cortexa53-xilinx-linux/example-interfaces/0.12.0-3/temp/run.do_compile.1049629, line 165
| 	#2: cmake_do_compile, /scratch/sandeep/yocto/2024.2/yp-dev/build-ros/tmp/work/cortexa72-cortexa53-xilinx-linux/example-interfaces/0.12.0-3/temp/run.do_compile.1049629, line 159
| 	#3: do_compile, /scratch/sandeep/yocto/2024.2/yp-dev/build-ros/tmp/work/cortexa72-cortexa53-xilinx-linux/example-interfaces/0.12.0-3/temp/run.do_compile.1049629, line 154
| 	#4: main, /scratch/sandeep/yocto/2024.2/yp-dev/build-ros/tmp/work/cortexa72-cortexa53-xilinx-linux/example-interfaces/0.12.0-3/temp/run.do_compile.1049629, line 178
ERROR: Task (/scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/../meta-ros/meta-ros2-jazzy/generated-recipes/example-interfaces/example-interfaces_0.12.0-3.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3124 tasks of which 3099 didn't need to be rerun and 1 failed.

This is due to missing target build dependencies. Hence add action-msgs
as a build dependency to prevent linking against action-msgs-native
libraries.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>