{jazzy} python-qt-binding: Fix PROVIDES parse issue
Building python-qt-binding fails with below parse issue

ERROR: Nothing PROVIDES 'python3-pyqt5-native' (but /scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/../meta-ros/meta-ros2-jazzy/generated-recipes/python-qt-binding/python-qt-binding_2.2.0-2.bb DEPENDS on or otherwise requires it). Close matches:
  python3-py-native
  python3-pytz-native
  python3-pyzmq-native
ERROR: Required build target 'python-qt-binding' has no buildable providers.
Missing or unbuildable dependency chain was: ['python-qt-binding', 'python3-pyqt5-native']
ERROR: Nothing PROVIDES 'sip3-native' (but /scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/../meta-ros/meta-ros2-jazzy/generated-recipes/python-qt-binding/python-qt-binding_2.2.0-2.bb DEPENDS on or otherwise requires it). Close matches:
  assimp-native
  sip-native
  zip-native
ERROR: Required build target 'python-qt-binding' has no buildable providers.
Missing or unbuildable dependency chain was: ['python-qt-binding', 'sip3-native']

This is due to python3-pyqt5-native and sip3-native packages are not
available in meta-qt5 scrathgap release. Hence remove this dependency
packages.

Also fix spdx errors and disable buildpaths QA check warnings.

WARNING: python-qt-binding-2.2.0-2-r0 do_populate_lic: QA Issue: python-qt-binding: No generic license file exists for: BSD in any provider [license-exists]
WARNING: python-qt-binding-2.2.0-2-r0 do_package: QA Issue: python-qt-binding: No generic license file exists for: BSD in any provider [license-exists]
ERROR: python-qt-binding-2.2.0-2-r0 do_create_spdx: Cannot find any text for license BSD
ERROR: Logfile of failure stored in: /scratch/sandeep/yocto/2024.2/yp-dev/build-ros/tmp/work/cortexa72-cortexa53-xilinx-linux/python-qt-binding/2.2.0-2/temp/log.do_create_spdx.1679155
ERROR: Task (/scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/../meta-ros/meta-ros2-jazzy/generated-recipes/python-qt-binding/python-qt-binding_2.2.0-2.bb:do_create_spdx) failed with exit code '1'
WARNING: python-qt-binding-2.2.0-2-r0 do_package_qa: QA Issue: File /opt/ros/jazzy/share/ament_index/resource_index/parent_prefix_path/python_qt_binding in package python-qt-binding contains reference to TMPDIR [buildpaths]

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>